### ISSUE TITLE
이 프로젝트에 필요한 개념 스터디 공지

### ISSUE THREAD

**Issue by DPS0340** [Naesung/iso-subway#1]
## 요약
지하철의 경로 찾기를 구현하기 위한 필수적인 이론을 배우는것을 목표로 합니다.
## 배울 것들
[이지호] [오후 11:57] 그럼
[이지호] [오후 11:57] 그래프 자료구조의 이해
[이지호] [오후 11:58] 자바스크립트로 그래프 구현체 만들기
[이지호] [오후 11:58] 최단 경로 알고리즘의 정의
[이지호] [오후 11:58] 다익스트라 알고리즘 이해 & 코딩
[이지호] [오후 11:58] 이정도 하면 되지않아?
## 방법, 일정
기여자들끼리 주말에 온라인으로 만납니다.
개념 이해 & 직접 코딩을 해보는 것이 목적입니다.

<hr/>

**이 스터디가 끝났다면 이 이슈를 닫아주세요.**

**Comment by Naesung** [comment]
> 닫기 싫은데
